// -----------------------------------------------------------------------------
// Script Name: programs.js
// Module:      Program Library
// Stack:       JavaScript (ES2020), no dependencies
// Description: The catalogue of every assembly program in this repository,
//              grouped by the folder it lives in.
//
//              GENERATED. Do not edit by hand: run "npm run index" after adding
//              or removing a program, and library.test.mjs will fail the build
//              if this file and the folders ever disagree.
//
//              This is an index, not a copy. The interface fetches the real
//              .asm file from the folder beside this one, so what the simulator
//              runs is what the repository actually holds.
//
//              449 programs across 39 categories.
//
// Authors:     Amey Thakur
// Repository:  https://github.com/Amey-Thakur/8086-ASSEMBLY-LANGUAGE-PROGRAMS
// License:     CC BY 4.0
// -----------------------------------------------------------------------------

'use strict';

/** Category name to the files it contains, in the order they appear on disk. */
export const PROGRAMS = {
    'Addressing Modes': ['based_addressing_mode.asm', 'based_indexed_addressing_mode.asm', 'based_indexed_with_displacement.asm', 'comprehensive_8086_addressing_modes_reference.asm', 'direct_addressing_mode.asm', 'immediate_addressing_mode.asm', 'indexed_addressing_mode.asm', 'register_addressing_mode.asm', 'register_indirect_addressing_mode.asm', 'relative_addressing_mode.asm', 'segment_override_addressing.asm', 'string_addressing_mode.asm'],
    'Arithmetic': ['add_array_of_bytes_from_memory.asm', 'addition_16bit_packed_bcd.asm', 'addition_16bit_simple.asm', 'addition_16bit_with_carry_detection.asm', 'addition_8bit_with_user_input.asm', 'calculate_sum_of_first_n_natural_numbers.asm', 'count_set_bits_in_16bit_binary.asm', 'decimal_adjust_after_addition_demo.asm', 'division_16bit_dividend_by_8bit_divisor.asm', 'generate_multiplication_table_for_number.asm', 'multiplication_8bit_unsigned.asm', 'signed_addition_and_subtraction_demo.asm', 'subtraction_8bit_with_user_input.asm', 'swap_two_numbers_using_registers.asm'],
    'Array Operations': ['array_equality_check.asm', 'calculate_sum_of_array_elements.asm', 'copy_block_of_data_between_arrays.asm', 'count_odd_and_even_numbers_in_array.asm', 'delete_element_from_array_by_index.asm', 'element_frequency_count.asm', 'find_maximum_element_in_array.asm', 'find_minimum_element_in_array.asm', 'insert_element_into_array_at_index.asm', 'interleave_two_arrays.asm', 'leaders_in_array.asm', 'maximum_subarray_sum.asm', 'move_zeros_to_end.asm', 'pair_with_given_sum.asm', 'prefix_sums.asm', 'remove_duplicates_from_sorted.asm', 'rotate_array_left.asm', 'rotate_array_right.asm', 'second_largest_element.asm', 'split_array_by_condition.asm'],
    'BIOS Services': ['bios_boot_and_system.asm', 'bios_character_with_attribute.asm', 'bios_clear_screen.asm', 'bios_cursor_control.asm', 'bios_keyboard_status.asm', 'bios_keyboard_wait.asm', 'bios_scan_code_table.asm', 'bios_shift_key_state.asm', 'bios_teletype_output.asm', 'bios_timer_ticks.asm', 'bios_versus_dos_output.asm', 'bios_video_mode_query.asm'],
    'Bit Manipulation': ['check_power_of_two.asm', 'count_set_bits_kernighan.asm', 'extract_bit_field.asm', 'isolate_lowest_set_bit.asm', 'reverse_bits_in_word.asm', 'swap_nibbles_in_byte.asm'],
    'Bitwise Operations': ['bitwise_and_logic_demonstration.asm', 'bitwise_logical_shift_left_and_multiplication.asm', 'bitwise_logical_shift_right_and_division.asm', 'bitwise_not_ones_complement_demonstration.asm', 'bitwise_or_logic_demonstration.asm', 'bitwise_rotate_left_circular_shift.asm', 'bitwise_rotate_right_circular_shift.asm', 'bitwise_xor_logic_demonstration.asm'],
    'Conditional Jumps': ['indirect_jump_through_register.asm', 'jcxz_guard_before_a_loop.asm', 'jump_if_equal_or_not_equal.asm', 'jump_on_carry_flag.asm', 'jump_on_overflow_flag.asm', 'jump_on_parity_flag.asm', 'jump_on_sign_flag.asm', 'short_jump_range_and_bridging.asm', 'signed_comparison_family.asm', 'signed_versus_unsigned_trap.asm', 'test_instruction_before_branch.asm', 'unsigned_comparison_family.asm'],
    'Control Flow': ['conditional_branching_and_status_flags.asm', 'for_loop_counter_iteration_pattern.asm', 'if_then_else_conditional_logic_structure.asm', 'loop_instruction_cx_register_control.asm', 'switch_case_multiway_branching_logic.asm', 'unconditional_jump_and_program_redirection.asm', 'while_loop_pre_test_conditional_iteration.asm'],
    'Conversion': ['ascii_to_integer.asm', 'bcd_to_ascii_and_back.asm', 'binary_to_decimal.asm', 'binary_to_hexadecimal_text.asm', 'celsius_fahrenheit_temperature_converter.asm', 'convert_decimal_to_binary_representation.asm', 'convert_decimal_to_octal_representation.asm', 'convert_hexadecimal_to_decimal_string.asm', 'convert_hexadecimal_to_packed_bcd.asm', 'convert_packed_bcd_to_hexadecimal.asm', 'decimal_to_any_base.asm', 'decimal_to_roman_numerals.asm', 'gray_code_conversion.asm', 'hex_string_to_value.asm', 'hex_to_seven_segment_decoder_lookup.asm', 'number_to_words.asm', 'reverse_digits_of_integer_value.asm', 'roman_numerals_to_decimal.asm', 'seconds_to_time_of_day.asm', 'string_comparison_lexicographical_check.asm', 'string_copy_using_manual_loop_iteration.asm', 'string_copy_using_movsb_instruction.asm', 'temperature_scales.asm'],
    'DOS Services': ['dos_buffered_input_0ah.asm', 'dos_create_and_write_file.asm', 'dos_delete_file.asm', 'dos_direct_console_06h.asm', 'dos_exit_codes.asm', 'dos_get_date_and_time.asm', 'dos_menu_driven_program.asm', 'dos_password_masking.asm', 'dos_print_string_09h.asm', 'dos_read_character.asm', 'dos_read_file.asm', 'dos_write_to_handle.asm'],
    'Data Structures': ['balanced_parentheses.asm', 'binary_tree_in_array.asm', 'circular_queue.asm', 'deque_double_ended.asm', 'evaluate_postfix.asm', 'hash_table_linear_probing.asm', 'infix_to_postfix.asm', 'linked_list_in_memory.asm', 'priority_queue_by_insertion.asm', 'queue.asm', 'set_union_and_intersection.asm', 'stack_array.asm', 'stack_using_pointer.asm', 'stack_with_minimum.asm'],
    'Data Transfer': ['in_out_port_transfer.asm', 'lahf_sahf_flag_transfer.asm', 'lds_les_far_pointers.asm', 'lea_versus_offset.asm', 'mov_between_registers.asm', 'mov_immediate_forms.asm', 'mov_memory_and_register.asm', 'mov_segment_registers.asm', 'push_pop_stack_order.asm', 'pushf_popf_preserve_flags.asm', 'xchg_swap_without_temporary.asm', 'xlat_lookup_table.asm'],
    'Expression': ['average_of_array.asm', 'calculator.asm', 'check_even_odd.asm', 'count_vowels.asm', 'count_words.asm', 'factorial.asm', 'fibonacci.asm', 'gcd_two_numbers.asm', 'power.asm', 'prime_number_check.asm', 'reverse_array.asm', 'string_concatenation.asm', 'substring_search.asm'],
    'External Devices': ['keyboard.asm', 'led_display_test.asm', 'mouse.asm', 'robot.asm', 'stepper_motor.asm', 'thermometer.asm', 'timer.asm', 'traffic_lights.asm', 'traffic_lights_advanced.asm'],
    'File Operations': ['append_to_file.asm', 'copy_file_contents.asm', 'create_file.asm', 'delete_file.asm', 'file_error_handling.asm', 'file_random_access_records.asm', 'file_size_by_seek.asm', 'open_existing_file.asm', 'read_file.asm', 'read_file_in_chunks.asm', 'rename_and_delete_file.asm', 'write_file.asm'],
    'Flags': ['carry_flag.asm', 'overflow_flag.asm', 'parity_flag.asm', 'sign_flag.asm', 'zero_flag.asm'],
    'Graphics': ['bitmap_sprite_drawing.asm', 'bresenham_line_algorithm.asm', 'colored_text.asm', 'colour_attribute_table.asm', 'draw_line.asm', 'draw_pixel.asm', 'draw_rectangle.asm', 'screen_clear_and_scroll.asm', 'text_mode_bar_chart.asm', 'text_mode_box_drawing.asm', 'vertical_histogram_with_axis.asm', 'vga_mode_13h_pixels.asm'],
    'Input Output': ['display_binary.asm', 'display_decimal.asm', 'display_hex.asm', 'read_number.asm'],
    'Interrupts': ['bios_cursor_position.asm', 'bios_keyboard.asm', 'bios_system_time.asm', 'bios_video_mode.asm', 'dos_display_char.asm', 'dos_display_string.asm', 'dos_read_char.asm', 'dos_read_string.asm'],
    'Introduction': ['data_definition_demo.asm', 'display_characters.asm', 'display_string_direct.asm', 'display_system_time.asm', 'hello_world_dos.asm', 'hello_world_interrupt.asm', 'hello_world_procedure.asm', 'hello_world_procedure_advanced.asm', 'hello_world_string.asm', 'hello_world_vga.asm', 'keyboard_wait_input.asm', 'mov_instruction_demo.asm', 'print_alphabets.asm', 'procedure_demo.asm', 'procedure_multiplication.asm'],
    'Loops': ['countdown_versus_countup.asm', 'loop_counted_with_cx.asm', 'loop_over_two_arrays.asm', 'loop_skipping_elements.asm', 'loop_unrolling.asm', 'loop_walking_an_array.asm', 'loop_with_computed_step.asm', 'loop_with_early_exit.asm', 'loope_repeat_while_equal.asm', 'loopne_search_until_found.asm', 'nested_loops_multiplication_table.asm', 'post_test_loop.asm'],
    'Macros': ['conditional_assembly_switches.asm', 'conditional_macros.asm', 'macro_building_data_tables.asm', 'macro_expansion_pitfalls.asm', 'macro_library_of_helpers.asm', 'macro_local_labels.asm', 'macro_repeat_and_fill.asm', 'macro_versus_procedure.asm', 'macro_with_parameters.asm', 'macro_with_register_argument.asm', 'nested_macros.asm', 'print_string_macro.asm'],
    'Mathematics': ['armstrong_number.asm', 'lcm.asm', 'perfect_number.asm', 'square_root.asm', 'twos_complement.asm'],
    'Matrix': ['matrix_addition.asm', 'matrix_determinant.asm', 'matrix_is_identity.asm', 'matrix_is_symmetric.asm', 'matrix_largest_and_smallest.asm', 'matrix_multiplication.asm', 'matrix_rotate_ninety_degrees.asm', 'matrix_row_and_column_sums.asm', 'matrix_scalar_multiply.asm', 'matrix_sparse_count.asm', 'matrix_subtraction.asm', 'matrix_trace_and_diagonals.asm', 'matrix_transpose.asm', 'matrix_upper_lower_triangular.asm'],
    'Memory Operations': ['block_copy.asm', 'memory_compare.asm', 'memory_fill.asm', 'memory_scan.asm'],
    'Number Theory': ['binomial_coefficient.asm', 'classify_by_divisor_sum.asm', 'collatz_sequence_length.asm', 'coprime_check.asm', 'count_divisors.asm', 'digital_root.asm', 'happy_number_check.asm', 'modular_exponentiation.asm', 'prime_factorisation.asm', 'sieve_of_eratosthenes.asm', 'sum_of_squares_and_cubes.asm', 'triangular_numbers.asm'],
    'Patterns': ['alphabet_triangle.asm', 'binary_pattern.asm', 'butterfly_pattern.asm', 'diamond_pattern.asm', 'floyd_triangle.asm', 'hollow_pyramid.asm', 'hollow_square.asm', 'hourglass_pattern.asm', 'inverted_triangle.asm', 'multiplication_grid.asm', 'number_pyramid.asm', 'pascal_triangle.asm', 'pyramid_of_stars.asm', 'right_aligned_triangle.asm', 'spiral_matrix_print.asm', 'triangle_pattern.asm'],
    'Port Programming': ['adc_read_and_scale.asm', 'buzzer_tone_pattern.asm', 'dac_ramp_and_triangle.asm', 'keypad_matrix_scan.asm', 'led_running_light.asm', 'port_word_versus_byte.asm', 'relay_control_bank.asm', 'seven_segment_display.asm', 'stepper_motor_full_step.asm', 'stepper_motor_half_step.asm', 'traffic_light_state_table.asm', 'water_level_controller.asm'],
    'Procedures': ['basic_procedure.asm', 'local_variables.asm', 'nested_procedures.asm', 'procedure_parameters.asm', 'recursive_factorial.asm'],
    'Recursion': ['binary_search_recursive.asm', 'factorial_recursive_frames.asm', 'fibonacci_recursive.asm', 'gcd_recursive.asm', 'mutual_recursion_even_odd.asm', 'power_recursive.asm', 'recursion_versus_iteration.asm', 'reverse_string_recursive.asm', 'stack_frame_anatomy.asm', 'sum_array_recursive.asm', 'sum_of_digits_recursive.asm', 'tower_of_hanoi.asm'],
    'Searching': ['binary_search.asm', 'binary_search_insertion_point.asm', 'character_occurrences_count.asm', 'count_occurrences_by_bisection.asm', 'exponential_search.asm', 'find_duplicate_number.asm', 'find_first_and_last_occurrence.asm', 'find_missing_number.asm', 'jump_search.asm', 'linear_search.asm', 'linear_search_all_matches.asm', 'search_element_array.asm', 'search_in_sorted_matrix.asm', 'search_rotated_sorted_array.asm', 'sentinel_linear_search.asm', 'ternary_search.asm'],
    'Shift and Rotate': ['arithmetic_shift_signed_divide.asm', 'multiply_by_ten_using_shifts.asm', 'overflow_flag_on_single_shift.asm', 'pack_two_bytes_into_word.asm', 'rotate_left_no_carry.asm', 'rotate_right_through_carry.asm', 'rotate_through_carry_multiword_shift.asm', 'rotate_to_test_each_bit.asm', 'shift_left_to_multiply.asm', 'shift_right_to_divide_unsigned.asm', 'unpack_word_into_two_bytes.asm', 'variable_shift_count_in_cl.asm'],
    'Signed Arithmetic': ['absolute_value.asm', 'sign_extension_cbw_cwd.asm', 'signed_array_average.asm', 'signed_byte_arithmetic.asm', 'signed_divide_idiv.asm', 'signed_minimum_and_maximum.asm', 'signed_multiply_imul.asm', 'signed_overflow_detection.asm', 'signed_range_check.asm', 'signed_sorting_by_value.asm', 'signed_versus_shift_division.asm', 'two_complement_representation.asm'],
    'Simulation': ['conveyor_belt_counter.asm', 'digital_clock_simulation.asm', 'fire_monitoring_system.asm', 'garment_defect.asm', 'lift_controller.asm', 'parking_lot_occupancy.asm', 'seven_segment_display_driver.asm', 'temperature_controller.asm', 'traffic_light_controller.asm', 'vending_machine.asm', 'washing_machine_cycle.asm', 'water_level_controller.asm'],
    'Sorting': ['array_ascending.asm', 'array_descending.asm', 'bubble_sort.asm', 'bubble_sort_with_early_exit.asm', 'check_if_sorted.asm', 'cocktail_shaker_sort.asm', 'counting_sort.asm', 'find_kth_smallest.asm', 'gnome_sort.asm', 'insertion_sort.asm', 'insertion_sort_word_array.asm', 'merge_sort_bottom_up.asm', 'merge_two_sorted_arrays.asm', 'selection_sort.asm', 'selection_sort_word_array.asm', 'sort_bytes_ascending.asm', 'sort_descending_order.asm'],
    'Stack Operations': ['balanced_brackets_check.asm', 'inspect_stack_registers.asm', 'last_in_first_out_order.asm', 'passing_arguments_on_stack.asm', 'push_pop.asm', 'reverse_string_stack.asm', 'save_all_registers.asm', 'save_and_restore_flags.asm', 'stack_depth_measurement.asm', 'stack_frame_with_bp.asm', 'stack_pointer_movement.asm', 'swap_using_stack.asm'],
    'String Instructions': ['cmpsb_compare_strings.asm', 'count_character_occurrences.asm', 'lodsb_process_each_byte.asm', 'movsb_copy_a_string.asm', 'movsw_copy_words.asm', 'overlapping_copy_with_direction.asm', 'palindrome_with_string_instructions.asm', 'reverse_string_with_pointers.asm', 'scasb_find_a_character.asm', 'segment_override_on_source.asm', 'stosb_fill_a_buffer.asm', 'string_length_with_scasb.asm'],
    'String Operations': ['caesar_cipher.asm', 'capitalise_each_word.asm', 'character_frequency_table.asm', 'check_anagram.asm', 'count_letters_digits_others.asm', 'longest_word_in_sentence.asm', 'palindrome_check.asm', 'remove_duplicate_characters.asm', 'replace_character.asm', 'reverse_words_in_sentence.asm', 'run_length_encoding.asm', 'string_contains_substring.asm', 'string_length.asm', 'string_reverse.asm', 'to_lowercase.asm', 'to_uppercase.asm', 'trim_spaces.asm'],
    'Utilities': ['beep_sound.asm', 'clear_screen.asm', 'delay_timer.asm', 'display_date.asm', 'password_input.asm']
};

/** How many programs the library holds. Written out so that anything quoting
 *  the number reads it from here rather than repeating it. */
export const PROGRAM_COUNT = 449;

/** How many categories they are grouped into. */
export const CATEGORY_COUNT = 39;
