// -----------------------------------------------------------------------------
// Script Name: library.test.mjs
// Module:      Conformance Suite, library index
// Stack:       Node.js (ES modules), no test framework
// Description: Checks that every program in the repository is reachable from
//              the simulator, and that the simulator lists nothing that is not
//              there.
//
//              A program that exists on disk but is missing from programs.js is
//              invisible: it is in the repository and cannot be opened from the
//              interface. A program listed but absent is worse, because
//              choosing it produces a failed fetch and an error message.
//
//              Neither can be caught by reading the code, and both happen the
//              moment the index is maintained by hand. So the index is
//              generated by "npm run index" and compared here.
//
// Authors:     Amey Thakur
// Repository:  https://github.com/Amey-Thakur/8086-ASSEMBLY-LANGUAGE-PROGRAMS
// License:     CC BY 4.0
// -----------------------------------------------------------------------------

import { readFileSync }    from 'node:fs';
import { join, dirname }  from 'node:path';
import { fileURLToPath }  from 'node:url';

import { readCatalogue }                             from '../tools/index-programs.mjs';
import { Assembler }                                from '../asm/assembler.js';
import { CPU }                                      from '../cpu/cpu.js';
import { Executor }                                 from '../exec/executor.js';
import { PROGRAMS, PROGRAM_COUNT, CATEGORY_COUNT }   from '../../programs.js';

const here       = dirname(fileURLToPath(import.meta.url));
const sourceRoot = join(here, '..', '..', '..');

let passed = 0;
let failed = 0;

function check(name, actual, expected) {
    if (JSON.stringify(actual) === JSON.stringify(expected)) { passed++; return; }

    failed++;
    console.log(`  FAIL  ${name}`);
    console.log(`          expected ${JSON.stringify(expected)}`);
    console.log(`          got      ${JSON.stringify(actual)}`);
}

// -----------------------------------------------------------------------------
console.log('\nTHE LIBRARY INDEX AGAINST THE FOLDERS');
// -----------------------------------------------------------------------------
const onDisk = readCatalogue(sourceRoot);

/** Flatten a catalogue to a sorted list of "Category/file.asm". */
function flatten(catalogue) {
    return Object.entries(catalogue)
        .flatMap(([category, files]) => files.map(file => `${category}/${file}`))
        .sort();
}

const diskList  = flatten(onDisk);
const indexList = flatten(PROGRAMS);

const missing = diskList.filter(name => !indexList.includes(name));
const phantom = indexList.filter(name => !diskList.includes(name));

check('every program on disk is listed in the index', missing, []);
check('every program in the index exists on disk',    phantom, []);

if (missing.length) {
    console.log('          run "npm run index" to add them');
}

// -----------------------------------------------------------------------------
console.log('\nTHE COUNTS THE INDEX PUBLISHES');
// -----------------------------------------------------------------------------
check('PROGRAM_COUNT matches the list',  PROGRAM_COUNT,  indexList.length);
check('CATEGORY_COUNT matches the list', CATEGORY_COUNT, Object.keys(PROGRAMS).length);
check('the index and the folders agree', indexList.length, diskList.length);

console.log(`\n  ${diskList.length} programs across ${Object.keys(onDisk).length} categories`);

// -----------------------------------------------------------------------------
console.log('\nNAMING');
// -----------------------------------------------------------------------------

// A path that needs escaping in a URL is not wrong, but it is worth knowing
// about, because the interface has to encode each segment separately.
const awkward = diskList.filter(name => /[?#%]/.test(name));

check('no program name needs unusual URL escaping', awkward, []);

const duplicates = indexList.filter((name, index) => indexList.indexOf(name) !== index);

check('no program is listed twice', duplicates, []);

// -----------------------------------------------------------------------------
console.log('\nNO PROGRAM DUPLICATES ANOTHER');
//
// Two files with different names doing exactly the same thing would inflate the
// count without adding anything, and would leave whichever one nobody noticed to
// rot. Neither the index nor the folder listing can see that, so the bodies and
// the titles are compared here.
// -----------------------------------------------------------------------------
const byBody  = new Map();
const byTitle = new Map();

for (const name of diskList) {
    const text = readFileSync(join(sourceRoot, name), 'utf8');

    // Comments, blank lines and indentation differ harmlessly between files, so
    // the comparison is made on the instructions and data alone.
    const code = text
        .split(/\r?\n/)
        .map(line => line.replace(/;.*$/, '').trim().toUpperCase())
        .filter(line => line !== '')
        .join('\n');

    const title = text.match(/^;\s*TITLE:\s*(.+)$/m)?.[1].trim() ?? `(no title in ${name})`;

    if (!byBody.has(code))   byBody.set(code, []);
    if (!byTitle.has(title)) byTitle.set(title, []);

    byBody.get(code).push(name);
    byTitle.get(title).push(name);
}

const sameBody  = [...byBody.values()].filter(names => names.length > 1);
const sameTitle = [...byTitle.values()].filter(names => names.length > 1);

check('no two programs have the same code', sameBody,  []);
check('no two programs have the same title', sameTitle, []);

// Every program should carry the authorship header the repository standardised
// on, because that header is what makes a file readable on its own.
const headerless = diskList.filter(name => {
    const text = readFileSync(join(sourceRoot, name), 'utf8');

    return !/^;\s*TITLE:/m.test(text) || !/^;\s*AUTHOR:/m.test(text);
});

check('every program carries a title and an author', headerless, []);

// -----------------------------------------------------------------------------
console.log('\nTHE PROGRAM THE EDITOR OPENS WITH');
//
// It is the first thing anybody sees, and somebody meeting the 8086 for the
// first time will press Run before reading anything. If it did not assemble, the
// simulator would look broken before it had been used at all. So it is held to
// the same standard as every program in the library.
// -----------------------------------------------------------------------------
{
    const appSource = readFileSync(join(here, '..', 'ui', 'app.js'), 'utf8');
    const welcome   = appSource.match(/const WELCOME = `([\s\S]*?)`;/)?.[1];

    check('the welcome program was found in app.js', typeof welcome, 'string');

    if (welcome) {
        const program = new Assembler().assemble(welcome);

        check('it assembles with no diagnostics', program.diagnostics.map(String), []);

        if (program.ok) {
            const cpu = new CPU();

            cpu.memory.load(cpu.registers.get('DS') << 4, program.data);
            cpu.registers.set('IP', program.entryPoint);
            new Executor(cpu, program).run(100_000);

            check('it prints its greeting', cpu.consoleOutput, 'Hello from the 8086.\n');
            check('it ends by returning to DOS', cpu.halted, true);
            check('with an exit code of zero',   cpu.exitCode, 0);
        }

        // It is meant to teach, so the two mistakes it warns about must actually
        // be described in it. A silent edit that dropped the commentary would
        // leave a Hello World that no longer explains anything.
        check('it explains the dollar terminator', /dollar sign/i.test(welcome), true);
        check('it explains LEA against MOV',       /LEA/.test(welcome),         true);
    }
}

// -----------------------------------------------------------------------------
console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed === 0 ? 0 : 1);
