// -----------------------------------------------------------------------------
// Script Name: library.test.mjs
// Module:      Conformance Suite, library index
// Stack:       Node.js (ES modules), no test framework
// Description: Checks that every program in the repository is reachable from
//              the simulator, and that the simulator lists nothing that is not
//              there.
//
//              A program that exists on disk but is missing from programs.js is
//              invisible: it is in the repository and cannot be opened from the
//              interface. A program listed but absent is worse, because
//              choosing it produces a failed fetch and an error message.
//
//              Neither can be caught by reading the code, and both happen the
//              moment the index is maintained by hand. So the index is
//              generated by "npm run index" and compared here.
//
// Authors:     Amey Thakur
// Repository:  https://github.com/Amey-Thakur/8086-ASSEMBLY-LANGUAGE-PROGRAMS
// License:     CC BY 4.0
// -----------------------------------------------------------------------------

import { join, dirname }  from 'node:path';
import { fileURLToPath }  from 'node:url';

import { readCatalogue }                             from '../tools/index-programs.mjs';
import { PROGRAMS, PROGRAM_COUNT, CATEGORY_COUNT }   from '../../programs.js';

const here       = dirname(fileURLToPath(import.meta.url));
const sourceRoot = join(here, '..', '..', '..');

let passed = 0;
let failed = 0;

function check(name, actual, expected) {
    if (JSON.stringify(actual) === JSON.stringify(expected)) { passed++; return; }

    failed++;
    console.log(`  FAIL  ${name}`);
    console.log(`          expected ${JSON.stringify(expected)}`);
    console.log(`          got      ${JSON.stringify(actual)}`);
}

// -----------------------------------------------------------------------------
console.log('\nTHE LIBRARY INDEX AGAINST THE FOLDERS');
// -----------------------------------------------------------------------------
const onDisk = readCatalogue(sourceRoot);

/** Flatten a catalogue to a sorted list of "Category/file.asm". */
function flatten(catalogue) {
    return Object.entries(catalogue)
        .flatMap(([category, files]) => files.map(file => `${category}/${file}`))
        .sort();
}

const diskList  = flatten(onDisk);
const indexList = flatten(PROGRAMS);

const missing = diskList.filter(name => !indexList.includes(name));
const phantom = indexList.filter(name => !diskList.includes(name));

check('every program on disk is listed in the index', missing, []);
check('every program in the index exists on disk',    phantom, []);

if (missing.length) {
    console.log('          run "npm run index" to add them');
}

// -----------------------------------------------------------------------------
console.log('\nTHE COUNTS THE INDEX PUBLISHES');
// -----------------------------------------------------------------------------
check('PROGRAM_COUNT matches the list',  PROGRAM_COUNT,  indexList.length);
check('CATEGORY_COUNT matches the list', CATEGORY_COUNT, Object.keys(PROGRAMS).length);
check('the index and the folders agree', indexList.length, diskList.length);

console.log(`\n  ${diskList.length} programs across ${Object.keys(onDisk).length} categories`);

// -----------------------------------------------------------------------------
console.log('\nNAMING');
// -----------------------------------------------------------------------------

// A path that needs escaping in a URL is not wrong, but it is worth knowing
// about, because the interface has to encode each segment separately.
const awkward = diskList.filter(name => /[?#%]/.test(name));

check('no program name needs unusual URL escaping', awkward, []);

const duplicates = indexList.filter((name, index) => indexList.indexOf(name) !== index);

check('no program is listed twice', duplicates, []);

// -----------------------------------------------------------------------------
console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed === 0 ? 0 : 1);
