; TITLE: Current System Date Display
; DESCRIPTION: A program that retrieves the current system date from DOS and displays it in DD/MM/YYYY format.
; AUTHOR: Amey Thakur (https://github.com/Amey-Thakur)
; REPOSITORY: https://github.com/Amey-Thakur/8086-ASSEMBLY-LANGUAGE-PROGRAMS
; LICENSE: MIT License

.MODEL SMALL
.STACK 100H

.DATA
    MSG DB 'Current System Date (DD/MM/YYYY): $'
    SLASH DB '/$'
    NEWLINE DB 0DH, 0AH, '$'

.CODE
MAIN PROC
    ; Initialize the Data Segment
    MOV AX, @DATA
    MOV DS, AX
    
    ; Display introductory message
    LEA DX, MSG
    MOV AH, 09H
    INT 21H
    
    ; --- Retrieve System Date ---
    ; DOS Interrupt 21H, AH=2AH: Get System Date
    ; Returns: 
    ;   CX = Year (1980 through 2099)
    ;   DH = Month (1 through 12)
    ;   DL = Day (1 through 31)
    ;   AL = Day of Week (0=Sun, 1=Mon, ..., 6=Sat)
    MOV AH, 2AH
    INT 21H
    
    PUSH CX          ; Save Year for later display
    PUSH DX          ; Save Month and Day (DH=Month, DL=Day)
    
    ; 1. Display Day
    XOR AH, AH
    MOV AL, DL       ; Get Day from DL
    CALL PRINT_NUM
    
    ; Display Slash "/"
    LEA DX, SLASH
    MOV AH, 09H
    INT 21H
    
    ; 2. Display Month
    POP DX           ; Restore DH=Month
    XOR AH, AH
    MOV AL, DH       ; Get Month from DH
    CALL PRINT_NUM
    
    ; Display Slash "/"
    LEA DX, SLASH
    MOV AH, 09H
    INT 21H
    
    ; 3. Display Year
    POP AX           ; Restore CX (Year) into AX
    CALL PRINT_NUM
    
    ; Print Newline
    LEA DX, NEWLINE
    MOV AH, 09H
    INT 21H
    
    ; Clean termination
    MOV AH, 4CH
    INT 21H
MAIN ENDP

; --- PRINT_NUM PROC ---
; Function to print a multi-digit number in AX as decimal.
; Logic: Successive division by 10 and pushing remainders to stack.
PRINT_NUM PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    
    XOR CX, CX       ; Digit counter
    MOV BX, 10       ; Divisor
    
DIVIDE_LOOP:
    XOR DX, DX       ; Clear DX for division
    DIV BX           ; AX = Quotient, DX = Remainder
    PUSH DX          ; Push remainder (the digit) to stack
    INC CX           ; Increment digit count
    CMP AX, 0        ; Check if quotient is zero
    JNE DIVIDE_LOOP
    
DISPLAY_LOOP:
    POP DX           ; Pop the most significant digit first
    ADD DL, '0'      ; Convert to ASCII
    MOV AH, 02H      ; DOS function to print a character
    INT 21H
    LOOP DISPLAY_LOOP
    
    POP DX
    POP CX
    POP BX
    POP AX
    RET
PRINT_NUM ENDP

; =============================================================================
; NOTES:
; 1. SYSTEM CLOCK: DOS keeps track of the date using the BIOS Real-Time Clock 
;    chip. Function 2AH is the high-level way to access this data.
; 2. YEAR FORMAT: The year is returned as a 16-bit binary value (e.g., 2023).
; 3. DECIMAL CONVERSION: Since registers store values in hex/binary, we must 
;    manually convert them to decimal characters by dividing by 10.
; 4. STACK USAGE: The PRINT_NUM procedure uses the stack to reverse the digits 
;    generated by division (since LSD is generated first but MSD must be printed first).
; =============================================================================

END MAIN
